### PR TITLE
Fix date format in analyser_merge_power_plant_FR #1844

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by Famlam** [comment]
If the dates in the source are now in `/`-separated format, are the "-01-01" and "-12-31" checks still needed then?

**Comment by frodrigo** [comment]
> If the dates in the source are now in `/`-separated format, are the "-01-01" and "-12-31" checks still needed then?

Right. Need also format update. Thank you.

**Comment by Famlam** [comment]
Not startswith and the other way around? Since the format needs to be inverted after the split?
(If these data entries still exist)

**Comment by frodrigo** [comment]
> Not startswith and the other way around? Since the format needs to be inverted after the split? (If these data entries still exist)

Still right ! Sorry for too quick fixing.

**Pull request merged**
