### PR TITLE
Add configuration for merge_natural_FR. Solves #1233

### PR DESCRIPTION
**Pull request by archie83**

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank you.

**Comment by frodrigo** [comment]
I forgot to merge it. Done now. Merged but not deployed.

**Comment by archie83** [comment]
Still not deployed, or is there another problem ?

**Comment by frodrigo** [comment]
Yes. Deployed.

**Comment by archie83** [comment]
I can't see the new items in the osmose website.

**Comment by frodrigo** [comment]
But not publicly activated
http://osmose.openstreetmap.fr/fr/issues/open?item=8530&useDevItem=all
http://osmose.openstreetmap.fr/fr/map/#item=8530&useDevItem=all&zoom=10&lat=44.7769&lon=4.248&level=1%2C2%2C3 (buggy link)
Please have a look to result, first.

**Comment by archie83** [comment]
Maybe I'll have to increase the distance. For example, see Aven Vigneron and Aven de Beaulieu on this map:
http://osmose.openstreetmap.fr/fr/map/#item=8530&useDevItem=all&zoom=18&lat=43.754186&lon=6.7607&level=1%2C2%2C3&issue_uuid=954d9e36-6f9e-5a77-d47f-cd5dade25c36

I'll have a deeper look this evening.

**Comment by archie83** [comment]
I had a look, and everything seems OK (except the millesime of the BDTOPO).

**Comment by frodrigo** [comment]
Ok
@jocelynj we can enble item 8530

About millesime see https://github.com/osm-fr/osmose-backend/pull/1197

**Pull request merged**
