### PR TITLE
TagWatchFrViPofm.py : improve regexp

### PR DESCRIPTION
**Pull request by Marc-marc-marc**
related to #2345

### CODE REVIEW

**Comment by Famlam** [comment]
I think that, using the example you provided: `|altitude||{{tag|ele}} || tag ||`
The capture groups would only be [`"tag ||"`, None]
Instead of: [`"altitude"`, `"{{tag|ele}}"`, `"tag"`, None]

Perhaps you can add a test case as well?

**Comment by Famlam** [comment]
The fix in #2358 should also resolve this issue and all other issues listed in #2345
I hope you don't mind that this PR would become obsolete in that case?

**Comment by Famlam** [comment]
Implemented via #2358

**Comment by Marc-marc-marc** [comment]
> I hope you don't mind that this PR would become obsolete in that case?

that's fine, thanks

**Pull request closed without merging**
