### PR TITLE
Split Quebec

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by frodrigo** [comment]
cc @jocelynj
cc @matthewdarwin

Waiting for extract to be generated.

**Comment by jocelynj** [comment]
I'm seeing that Quebec relation, in addition to "Nord du Québec" doesn't contain a few islands along the coast: https://www.openstreetmap.org/relation/61549#map=11/56.4560/-76.5895

Are these islands in another Canadian Province?

**Comment by frodrigo** [comment]
Yes Nunavut
https://www.openstreetmap.org/relation/390840

**Comment by frodrigo** [comment]
@jocelynj the extract was generated yesterday, but the spited Quebec is not here.

**Pull request merged**
