### PR TITLE
detect bad value for tracktype

### LINKED ISSUE #1800: use "similar value" to detect typo in tracktype
value "grace3" could be detected as similar to grade3
and/or catch all values not matching "^grade[1-5]$"

### PR DESCRIPTION
**Pull request by Marc-marc-marc**
close #1800

### CODE REVIEW

**Review by Famlam — COMMENTED** [review]
You'll need to remove it from this list now that it's added as a tag with a 'closed' number of values

Edit: oops, this was supposed to be a line comment on line 67

**Comment by Marc-marc-marc** [comment]
thanks for the review

**Comment by Marc-marc-marc** [comment]
is it ok ?

**Comment by Famlam** [comment]
IMO yes, but I don't know if I'm allowed to merge it myself, @frodrigo @jocelynj ?

**Comment by frodrigo** [comment]
> IMO yes, but I don't know if I'm allowed to merge it myself, @frodrigo @jocelynj ?

Yes, it is also ok for me.  Yes, please, @Famlam you can merge it.

**Pull request merged**
