### PR TITLE
checking for ferry terminals instead of ferry routes.

### PR DESCRIPTION
**Pull request by ComradeRamen**
I started going through ferry route ends not tagged with these and will either fix them or relay back here.
Will give an update on progress tomorrow.

### CODE REVIEW

**Comment by ComradeRamen** [comment]
https://github.com/osm-fr/osmose-backend/issues/2166

**Comment by Famlam** [comment]
Hi,
Based on the description I suspect it's work in progress, so not reviewing the code yet, but would you expect slipways on bicycle paths, or secondary and above major roads? Slipways are for letting boats enter the water, which sounds wrong to me. (Imagine a high-priority motorway full of boat-carrying cars that all want to let their boat into the water there)

**Comment by ComradeRamen** [comment]
Out of 4476 connecting nodes only 138 didn't have the `amenity=ferry_terminal` tag which I have already fixed. From what I can tell this PR should now not throw any new issues and should also resolve any "false positives" where the ferry_terminal is mapped but not the ferry route.

**Comment by ComradeRamen** [comment]
Full [Script/s](https://pastebin.com/93EE3T40) used.

**Comment by Famlam** [comment]
Thanks! I think you can remove lines 57 to 62 and line 86
```sql
SELECT
    wid,
    nid,
    geom,
    highway
FROM (
```
```sql
) AS t
```

They don't serve a purpose anymore now that the JOIN on ferry routes is gone

**Comment by ComradeRamen** [comment]
Now I'm confused why node 158 isn't causing an extra error since its not tagged as a ferry terminal.

**Comment by ComradeRamen** [comment]
> can remove lines 57 to 62 and line 86

Done.

Btw I interpreted "Highway from `motorway` to `tertiary` are important ways. They should
lead to somewhere and in particular to a network of minor roads." as meaning tertiary roads are included in the check even tho they're not.

**Comment by Famlam** [comment]
> Btw I interpreted "Highway from `motorway` to `tertiary` are important ways. They should lead to somewhere and in particular to a network of minor roads." as meaning tertiary roads are included in the check even tho they're not.

The description is technically correct, because they *should* be connected, but it causes quite some issues in some less densely mapped areas for which I don't know better solutions. E.g. in sweden_gotland, for example https://www.openstreetmap.org/way/55408443 , on first glance I have the impression that the custom in this country is to map (nearly) all I-numbered roads as tertiary.
In addition, there's quite a couple of tertiaries that end in a `highway=construction` road which would all be flagged. It's very uncommon for an entire road to be mapped with a different classification only because there's a few months construction at a small part of the road.
Hence it's mentioned in the message that they should be connected, without actually giving a warning. 

> Done.

Thanks!

I'll give it a quick run on one or two countries later to be sure that there's no side effects (currently running something else...) but code-technically I don't have comments anymore.

**Comment by ComradeRamen** [comment]
Why are construction roads excluded from endpoints unlike class 3.

**Review by Famlam — APPROVED** [review]

**Pull request merged**
