### PR TITLE
oh_sanitizer: Raise the priority of 24/7 matches and add tests.

### PR DESCRIPTION
**Pull request by fgouget**
Signed-off-by: Francois Gouget <fgouget@free.fr>

### CODE REVIEW

**Comment by fgouget** [comment]
This will hopefully stop "24/7" from being interpreted as "24:00,07:00" as reported by deuzeffe in issue 433.
https://github.com/osm-fr/osmose-backend/issues/433#issuecomment-465766737

**Comment by frodrigo** [comment]
Thank for your quick fix.

**Comment by frodrigo** [comment]
I look like the problem isn't solved: 

http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3250&class=32501&start_date=2019-02

http://osmose.openstreetmap.fr/fr/errors/?item=3250&class=32501

**Comment by fgouget** [comment]
I have run the tests in Python 3 and I have gotten failures, including random ones. But none that seem related to the 24/7 case. I have fixed these failures and rerun the tests in both Python 2 and 3 a few hundred times and I don't get any failure now. I sent the fixes as a separate merge request.

Is Osmose running in Python 3 by any chance?

**Comment by frodrigo** [comment]
Still, running with python2, but actively working on python 3 port.
- https://github.com/frodrigo/osmose-backend/tree/py23
- https://github.com/frodrigo/osmose-backend/tree/py3

**Pull request merged**
