### PR TITLE
Import more Objects from Mapillary

### PR DESCRIPTION
**Pull request by fansanelli**
Hello,

Please note that this code is untested...
As discussed with @frodrigo Mapillary may still give too many false positive street objects.
Feel free to revert if someone complains.

Many thanks
Cheers,
Francesco

### CODE REVIEW

**Comment by frodrigo** [comment]
Ok. Let's try with this.

**Comment by frodrigo** [comment]
Please. Can you rebase this branch.

**Comment by fansanelli** [comment]
> Please. Can you rebase this branch.

is ok for you, now?

**Comment by frodrigo** [comment]
Merged. But not deployed, yet.

**Comment by frodrigo** [comment]
Back to normal and lot more with new objects
image

**Pull request merged**
