### PR TITLE
Add support checking Dutch (NL) house numbers

### PR DESCRIPTION
**Pull request by danfos**
I was seeing a warning generated for valid Dutch (NL) house numbers so did look up the documentation and added code to support checking Dutch (NL) house numbers.

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank. The community is agree on using a such strict format for addresses number?

**Comment by danfos** [comment]
I did not ping the community but the in the Netherlands almost all house data is imported from BAG, see https://wiki.openstreetmap.org/wiki/NL:BAG which is government data.

The link, https://imbag.github.io/catalogus/hoofdstukken/attributen--relaties#734-huisnummertoevoeging does specify the rules for that data and this PR is the implementation of that.

**Comment by frodrigo** [comment]
Ok. Thank.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/?country=netherlands_*&item=2060&class=10

Lot of issues are not raised (50 000 and still processing). Please check and fix the regex if required.

**Comment by danfos** [comment]
Yes, a lot of issues for 4 provinces while the other have almost none, including the one I live in which is the most populated.

Had a look at the problems and they seems to be all of the type "building=houseboot" or "landuse=static_caravan", but that data is also coming from BAG, so two possibilities, excluding these (my preference) or extending the rules so that also the number type of these objects is also allowed.

The Caribbean Islands probably have to be excluded as they seem to follow not the official rules. 

No more time for today, let me come back on it tomorrow-evening.

**Comment by frodrigo** [comment]
@danfos new issue about this https://github.com/osm-fr/osmose-backend/issues/711

**Pull request merged**
