### PR TITLE
[WIP] Import MISE dataset for italian fuel stations

### PR DESCRIPTION
**Pull request by fansanelli**
Hello,

please find the patch to import italian fuel stations.
Please note this is still untested.

Please let me know what you think
Many thanks
Cheers
Francesco

### CODE REVIEW

**Comment by frodrigo** [comment]
I made a working version and got this result: http://osm110.openstreetmap.fr/~fred/Analyser_Merge_Fuel_IT-italy_puglia.xml.bz2
Can you check it, especiality if the conflation distance is good.

**Comment by fansanelli** [comment]
> I made a working version and got this result: http://osm110.openstreetmap.fr/~fred/Analyser_Merge_Fuel_IT-italy_puglia.xml.bz2
> Can you check it, especiality if the conflation distance is good.

I mispelled the "ref", this is embarassing... anyhow:

'"Ip Services S.R.L."'

should now be "Ip Services S.R.L."

I've discussed with original author of imports and he also said that 300 is too high for Italy, so I took the value from his script:

https://github.com/cascafico/OSM-ItalyFuelStations/blob/master/profile-mise.py

Thanks for your help!

**Comment by frodrigo** [comment]
Commits cherry-picked.
Not deplyoed yet.

**Comment by frodrigo** [comment]
Deployed, processing still in progress.

http://osmose.openstreetmap.fr/en/errors/?country=italy*&item=8200,8201,8202

**Comment by frodrigo** [comment]
Sorry I forgot to setup the new analyser into the config. So back to the not yet deployed status.

**Comment by fansanelli** [comment]
Can you please turn it on? I'd love to take a look at the data during this weekend

**Comment by frodrigo** [comment]
It will be shipped by the next deployment done by @jocelynj

**Comment by fansanelli** [comment]
All right

**Comment by jocelynj** [comment]
it is pushed on master and on backends: https://github.com/osm-fr/osmose-backend/commit/909ea5cf9dc6325d8633f0b3170956721b17e277
Thanks!

**Comment by fansanelli** [comment]
Cool

**Comment by frodrigo** [comment]
It fails.

```
2020-02-14 21:06:12 italy_abruzzo : merge_fuel_IT
2020-02-14 21:06:12   error: error on analyse merge_fuel_IT...
2020-02-14 21:06:12     Traceback (most recent call last):
2020-02-14 21:06:12       File "./osmose_run.py", line 202, in execc
2020-02-14 21:06:12         with obj(analyser_conf, logger.sub()) as analyser_obj:
2020-02-14 21:06:12       File "/data/project/osmose/backend/analysers/analyser_merge_fuel_IT.py", line 40, in __init__
2020-02-14 21:06:12         separator = ';', skip_first_lines = 1, quote = '~'),
2020-02-14 21:06:12     TypeError: __init__() got an unexpected keyword argument 'skip_first_lines'
```

**Comment by frodrigo** [comment]
Add the missing code to skip the first line of the CSV.

**Comment by fansanelli** [comment]
Thank you guys! Now I can see gas stations popping out!

**Comment by frodrigo** [comment]
This result contain false positive like:
```diff
-operator = P.G. Ciardiello di Ciardiello Pina e Maria Gabriella -Società in Nome Collettivo 
+operator = P.G. Ciardiello Di Ciardiello Pina E Maria Gabriella -Societa' In Nome Collettivo 
```

**Comment by fansanelli** [comment]
Hi, do you think we should work to make the exact label of previous imports? or don't bother and check if lowercased text are same?

**Comment by frodrigo** [comment]
Did you have the code used for last import ?

Note there is not only the case, but also the "à".

**Comment by fansanelli** [comment]
It's done by openrefine... But I have never used it

**Pull request closed without merging**
