### PR TITLE
Indicate which tag has the wrong value

### PR DESCRIPTION
**Pull request by Famlam**
In case `turn:lanes:forward` and `turn:lanes:backward` co-exist, indicate the bad one

### CODE REVIEW

**Comment by Famlam** [comment]
Hmmm, are the tests broken or is it due to me?

p.s.: should the copyright notice be updated? It's not 2015 anymore :)

**Comment by Famlam** [comment]
> > Hmmm, are the tests broken or is it due to me?
> 
> You are right. I havn't push the fex, yet. Now is done. You can rebase to have it.

Done!

> > p.s.: should the copyright notice be updated? It's not 2015 anymore :)
> 
> Do not bother with what. But since you done many improv, please, add your name.

No need, but thanks :)

**Comment by frodrigo** [comment]
Thank. Merged, but not deployed yet.

**Comment by frodrigo** [comment]
Deployed

**Pull request merged**
