### PR TITLE
Fix concat: filter None values

### PR DESCRIPTION
**Pull request by Famlam**
See https://github.com/osm-fr/osmose-backend/commit/2e09042edea115e21ef64b66357af4815cea46a5#commitcomment-120494894

See the failed test messages on the current "dev" version of Github:
```
self = <plugins.Josm_wikipedia.Test testMethod=test>

    def test(self):
        n = Josm_wikipedia(None)
        class _config:
            options = {"country": None, "language": None}
        class father:
            config = _config()
        n.father = father()
        n.init(None)
        data = {'id': 0, 'lat': 0, 'lon': 0}
    
        self.check_err(n.node(data, {'wikipedia': 'Foobar'}), expected={'class': 9011001, 'subclass': 15[174](https://github.com/osm-fr/osmose-backend/actions/runs/5444546897/jobs/9902544502#step:10:175)50396})
        self.check_not_err(n.node(data, {'wikipedia': 'en-GB:Foobar'}), expected={'class': 9011001, 'subclass': 1517450396})
        self.check_not_err(n.node(data, {'wikipedia': 'en:Foobar'}), expected={'class': 9011001, 'subclass': 1517450396})
        self.check_err(n.node(data, {'wikipedia': 'X-Y-Z:Foobar'}), expected={'class': 9011002, 'subclass': [182](https://github.com/osm-fr/osmose-backend/actions/runs/5444546897/jobs/9902544502#step:10:183)69[184](https://github.com/osm-fr/osmose-backend/actions/runs/5444546897/jobs/9902544502#step:10:185)81})
        self.check_not_err(n.node(data, {'wikipedia': 'en:Foobar'}), expected={'class': 9011002, 'subclass': 1826918481})
        self.check_not_err(n.node(data, {'wikipedia': 'en:OpenStreetMap'}), expected={'class': 9011003, 'subclass': 75691825})
        self.check_err(n.node(data, {'wikipedia': 'http://en.wikipedia.org/wiki/OpenStreetMap'}), expected={'class': 9011003, 'subclass': 75691825})
        self.check_not_err(n.node(data, {'wikipedia': 'abe-x-old:foo'}), expected={'class': 9011004, 'subclass': 616152609})
        self.check_err(n.node(data, {'wikipedia': 'be-x-old:foo'}), expected={'class': 9011004, 'subclass': 616152609})
        self.check_err(n.node(data, {'wikipedia': 'cz:foo'}), expected={'class': 9011005, 'subclass': 243392039})
        self.check_not_err(n.node(data, {'wikipedia': 'en:cz:foo'}), expected={'class': 9011005, 'subclass': 243392039})
        self.check_err(n.node(data, {'wikimedia_commons': 'File:Foo%27s'}), expected={'class': 9011006, 'subclass': 1999051286})
        self.check_not_err(n.node(data, {'wikimedia_commons': 'File:Foo'}), expected={'class': 9011006, 'subclass': 1999051286})
        self.check_err(n.node(data, {'wikipedia': 'en:Foo%27s'}), expected={'class': 9011006, 'subclass': 83644825})
        self.check_not_err(n.node(data, {'wikipedia': 'en:Foo'}), expected={'class': 9011006, 'subclass': 83644825})
>       self.check_err(n.node(data, {'wikipedia:de': 'Foo%27s'}), expected={'class': 9011006, 'subclass': 556604422})

plugins/Josm_wikipedia.py:1164: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
plugins/Josm_wikipedia.py:[197](https://github.com/osm-fr/osmose-backend/actions/runs/5444546897/jobs/9902544502#step:10:198): in node
    (mapcss.concat(mapcss._tag_uncapture(capture_tags, '{0.key}'), '=', mapcss.get(mapcss.regexp_match(self.re_09a81144, mapcss.tag(tags, mapcss._tag_uncapture(capture_tags, '{0.key}'))), 1), mapcss.trim(mapcss.replace(mapcss.URL_decode(mapcss.get(mapcss.println(mapcss.regexp_match(self.re_644be9e0, mapcss.tag(tags, mapcss._tag_uncapture(capture_tags, '{0.key}')))), 2)), '_', ' ')))).split('=', 1)])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ('wikipedia:de', '=', '', None)

    def concat(*args):
        if args is not None:
>           return str_value(''.join(args))
E           TypeError: sequence item 3: expected str instance, NoneType found

modules/mapcss_lib.py:407: TypeError
----------------------------- Captured stdout call -----------------------------
['Foo%27s', '', 'Foo%27s']
```

### CODE REVIEW

**Comment by Famlam** [comment]
p.s. the remaining test fails because of a blacklisted, but removed rule.
Removing the blacklist is easy, but I'm a bit hesitant to update item_map.py until issue 1934 is fixed.

It would hardcode the bad line that's also here now:
https://github.com/osm-fr/osmose-backend/commit/2e09042edea115e21ef64b66357af4815cea46a5#diff-42d26fe5620eda6569a26e5d3009ff53d2f6c74be6de9d29d8cda451c547d7f1R37

**Comment by frodrigo** [comment]
Sorry, but unsure about what this PR is for.
I do not understand you comment https://github.com/osm-fr/osmose-backend/commit/2e09042edea115e21ef64b66357af4815cea46a5#commitcomment-120494894

**Comment by Famlam** [comment]
> Sorry, but unsure about what this PR is for.

The concat function is currently crashing due to the mapcss update. This is because the input that `concat` gets contains a `None` value. (The output I'm showing is from the pytest output on current Github dev/master)

It consists of two bugs:
1. `concat` getting a None value as 4th argument (see #1938 )
2. `concat` not removing None values (causing it to crash), which is this PR. The definition of JOSM is that concat should remove None values

**Comment by Famlam** [comment]
See also for example https://buildbot.osmose.openstreetmap.fr/#/builders/219/builds/1044/steps/3/logs/stdio

**Comment by frodrigo** [comment]
Ok. Thank you.

**Pull request merged**
