### PR TITLE
Add analyser merge_natural_FR

### PR DESCRIPTION
**Pull request by archie83**
Add a new analyser to merge data from BD ORTHO IGN relative to relief (orography).

### CODE REVIEW

**Comment by frodrigo** [comment]
Have you make it run?

Usualy we try to avoid low frequency items, think the query will be run each day forever on a server.

**Comment by archie83** [comment]
Yes, I tested it for the Alpes-Maritimes. Shouldn't it possible to run merge analysers less often, for example once a week?

**Comment by frodrigo** [comment]
> Yes, I tested it for the Alpes-Maritimes. Shouldn't it possible to run merge analysers less often, for example once a week?

We can, but we have no plan to do this. And here frequent and less frequent are in the same analyser so it cannot be  done in this away anyway.

**Comment by archie83** [comment]
I must admit that some elements, such as stones, are not very useful. Would it be acceptable if we keep only the most important ones, such as (by order of preference):
- Peaks
- Saddles
- Cave entrances and pits
- Capes
- Beaches
?

**Comment by frodrigo** [comment]
Yes. Good candidates are frequent and not prone to false positives.

**Comment by frodrigo** [comment]
Look good to me. Thank you.
Merged, but not deployed, yet.

**Comment by archie83** [comment]
Changes in the frontend are also required, aren't they? Item #8530 is not known in the frontend.

**Comment by frodrigo** [comment]
Yes, do not brother about that.

**Comment by frodrigo** [comment]
Deployed but but not run.
Miss declaration in configuration FR + oversee, can you make a PR please?

**Comment by archie83** [comment]
Is it enough to add two lines to osmose_config.py ?

**Comment by frodrigo** [comment]
Yes

**Pull request merged**
