### PR TITLE
Update merge_defibrillators_FR

### PR DESCRIPTION
**Pull request by PanierAvide**
Various improvements on GeoDAE defibrillators merge analyser :
- Use GeoJSON as source format (CSV was causing errors)
- Re-introduce `ref:FR:GeoDAE` as ID was stabilized on GeoDAE dataset (and confirmed by a check I've made at 2 weeks interval)
- Moved annex tags in mapping2 (by the way, [doc could be clarified](https://github.com/osm-fr/osmose-backend/blob/master/doc/4-Merge.md#mapping) on the true reason of separating mapping1 and 2, I'm not sure myself what it changes : mapping2 tags changes are not considered for updates selection ?)

### CODE REVIEW

**Comment by frodrigo** [comment]
>     * Moved annex tags in mapping2 (by the way, [doc could be clarified](https://github.com/osm-fr/osmose-backend/blob/master/doc/4-Merge.md#mapping) on the true reason of separating mapping1 and 2, I'm not sure myself what it changes : mapping2 tags changes are not considered for updates selection ?)

Yes, that the only point, change in mapping2 tags are not trigger an update suggestion. While there are still included in creation and update.

**Comment by frodrigo** [comment]
I see it, maybe not on all yet. We deploy yesterday.
http://osmose.openstreetmap.fr/fr/error/e2ab3b70-c023-412a-c017-0c82ac289d10

**Comment by PanierAvide** [comment]
Oh OK, I thought this was deployed before yesterday so that's why I was worried for it not being present. And what about items 8371 / 8372 ? Issues will also arrive in the following days ?

**Comment by frodrigo** [comment]
Still to be enabled https://github.com/osm-fr/osmose-backend/issues/1165#issuecomment-776919236

**Pull request merged**
