### PR TITLE
Deal with non-sequential indices

### PR DESCRIPTION
**Pull request by Famlam**
Issue #1603 

`mapcss._tag_capture(...)` captured `[key, value]` correctly, but `mapcss._value_capture(...)` then overwrote the capture with `[None, None]` (and only set the value itself, resulting in eventually `[None, value]`)

Also added a test to spot such issues in the future: if a `{` or `}` appears in the string, it'll complain.

### CODE REVIEW

**Comment by Famlam** [comment]
The effect of this PR on two countries can be seen here: https://github.com/Famlam/osmose-backend/commit/8f35ba67448cd137689fe142bf340aaa60e5f858

**Comment by frodrigo** [comment]
Ok.
Thank you for looking into this.

About the test. What do you thing of using a subclass for test for generated mapcss plugin in place of `disallowed_str_in_text` anywhere?

**Comment by frodrigo** [comment]
Ok.
Thank you for looking into this.

About the test. What do you thing of using a subclass for test for generated mapcss plugin in place of `disallowed_str_in_text` anywhere?

**Comment by Famlam** [comment]
> Ok. Thank you for looking into this.
> 
> About the test. What do you thing of using a subclass for test for generated mapcss plugin in place of `disallowed_str_in_text` anywhere?

I think that's a good idea ;). Initially I thought it may be a useful feature, but I can't really think of other plugins that would benefit. Done!

**Comment by frodrigo** [comment]
> > About the test. What do you thing of using a subclass for test for generated mapcss plugin in place of `disallowed_str_in_text` anywhere?
> 
> I think that's a good idea ;). Initially I thought it may be a useful feature, but I can't really think of other plugins that would benefit. Done!

Thank to change it this way.

**Pull request merged**
