### PR TITLE
Update Mapcss analysers

### PR DESCRIPTION
**Pull request by PanierAvide**
Updated MapCSS analysers, in particular FranceSpecificRules after discussion on motorway_junction on talk-fr.

### CODE REVIEW

**Comment by frodrigo** [comment]
Please keep only on this PR py file for mapcss you wan to update.
There is a bug #987 deleting rules in combinations.

**Comment by frodrigo** [comment]
Merged, But not deployed, yet.

**Comment by PanierAvide** [comment]
Thanks

**Comment by frodrigo** [comment]
Deployed

**Pull request merged**
