### PR TITLE
waterway=boatyard is on land

### PR DESCRIPTION
**Pull request by elgaard**

### CODE REVIEW

**Comment by jocelynj** [comment]
Could you rebase this branch on latest master, to remove the "merge" commit ?

**Comment by frodrigo** [comment]
@jocelynj on github you can swtich "Create a merge commit" to "Rebase and merge".

**Comment by frodrigo** [comment]
I think we must add mote tags: dam, lock_gate and recheck all queries from this analyser.

**Comment by frodrigo** [comment]
```diff
diff --git a/analysers/analyser_osmosis_highway_vs_building.py b/analysers/analyser_osmosis_highway_vs_building.py
index b1e9951..6633536 100644
--- a/analysers/analyser_osmosis_highway_vs_building.py
+++ b/analysers/analyser_osmosis_highway_vs_building.py
@@ -111,7 +111,7 @@ FROM
 WHERE
     tags != ''::hstore AND
     (
-        tags?'waterway' OR
+        tags?'waterway' AND tags->'waterway' IN ('stream', 'ditch', 'river', 'drain', 'canal', 'riverbank') OR
         (   
             tags?'natural' AND
             tags->'natural' = 'water'
```

**Comment by frodrigo** [comment]
I merge my version of code. The result is now on the Osmose-QA map. Can you confirm it's now ok for you?

**Pull request closed without merging**
