### PR TITLE
add missing modules to install command

### LINKED ISSUE #1141: Maybe mention extra packages needed for Ubuntu 20.04?
https://github.com/osm-fr/osmose-backend/blob/master/INSTALL.md#install on  Ubuntu 20.04 required also

`sudo apt-get install ninja-build libarchive-dev extra-cmake-modules flex bison` for PyKOpeningHours dependency that needed to be compiled. Is it worth mentioning?

Without that `pip install -r requirements.txt` was not completing successfully.

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #1141

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note: I added also `sudo` - maybe there was a good reason for not including it?

**Comment by frodrigo** [comment]
> Note: I added also `sudo` - maybe there was a good reason for not including it?

Other cmd does not have sudo, so keep this one as well.

**Comment by matkoniecz** [comment]
Done.

**Comment by frodrigo** [comment]
Thank you.

**Pull request merged**
