### PR TITLE
Update mapcss README.md

### PR DESCRIPTION
**Pull request by Famlam**
- Add download link for ANTLR
- Update command so it also works when ran in the Windows terminal (if not, I got all kind of unknown char messages as it doesn't default to utf8)
**Please do check that this doesn't affect anything poorly in Linux**

### CODE REVIEW

**Comment by frodrigo** [comment]
Maybe just add this at the start of faulting file
```
#-*- coding: utf-8 -*-
```

**Comment by frodrigo** [comment]
That nice to see some one deeping into that part of Osmose. Probably the most complicated one!

**Comment by Famlam** [comment]
> Maybe just add this at the start of faulting file
> 
> ```
> #-*- coding: utf-8 -*-
> ```

I just tried this, adding it to all Osmose files involved (leaving the python files that handle the read/write etc untouched), unfortunately doesn't work. I really need to specify the -X option.
```
C:\[...]\osmose-backend-master>python -m mapcss.update
https://josm.openstreetmap.de/josmfile?page=Rules/FranceSpecificRules
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\[...]\osmose-backend-master\mapcss\update.py", line 31, in <module>
    main(sys.argv[1:])
  File "C:\[...]\osmose-backend-master\mapcss\update.py", line 22, in main
    open(f, 'w').write(r.text)
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2289' in position 13245: character maps to <undefined>
```


> That nice to see some one deeping into that part of Osmose. Probably the most complicated one!

Yeah, very complicated README, was a huge challenge to get it pass all tests :)

**Comment by frodrigo** [comment]
Not sure about adding the `-X` option. Does we support windows ? I even surprised you are able to run some (all ?) part of it under windows. @jocelynj what do you think about this ?

**Comment by Famlam** [comment]
>I even surprised you are able to run some (all ?) part of it under windows

Yep, I was surprised too :)

**Comment by jocelynj** [comment]
On windows, is it possible to set LANG to something like en_US@UTF-8 to remove the need for "-X utf8"? Or setting variable PYTHONUTF8?

If not, and if this option doesn't break Linux, then we should add this option in the README, maybe with a comment to tell that it is for windows.

On the other side, we should add the missing `#-*- coding: utf-8 -*-` in all python files, just to be cleaner.

**Comment by Famlam** [comment]
> Or setting variable PYTHONUTF8?

I didn't know about this one yet, but this works perfectly!

**Comment by frodrigo** [comment]
> > Or setting variable PYTHONUTF8?
> 
> I didn't know about this one yet, but this works perfectly! I adjusted the PR, and incorporated the suggestion of @jocelynj. If you prefer not to mention Windows-specific things, that's fine for me too, then I'll remove that line

It is not mapcss specific and could be set in an other READEM/INTALL/doc part I think.

The `#-*- coding: utf-8 -*-` you added still necessary ? (I removed this such line in the frontend)

**Comment by Famlam** [comment]
>The #-*- coding: utf-8 -*- you added still necessary ? (I removed this such line in the frontend)

As far as I'm aware, it's only mandatory if you use unicode characters in the .py files directly. It however doesn't hurt either. So I'll let you and Jocelynj decide and adjust the code accordingly ;)

> It is not mapcss specific and could be set in an other READEM/INTALL/doc part I think.

Suggestions? (I haven't encountered issues with this anywhere else yet, but of course most files don't have read/write operations on external files containing i.e. ⊇ and such, except mapcss ;) )

**Pull request merged**
