### PR TITLE
Cosmectic improvement on TagFix_Housenumber.py

### PR DESCRIPTION
**Pull request by FredericBourgeon**
Putting Number between `` characters will format it with the <code> tag. A simple cosmetic improvement that will hopefully break nothing.

### CODE REVIEW

**Comment by Famlam** [comment]
I'm afraid this would suggest to people that they should put literally "Number" there, rather than 1, 2, 3 etc. So I wouldn't do this.

(Grammar-wise I think it should be "a number", but without these `-marks)

**Comment by FredericBourgeon** [comment]
Giving it a second thought and agreeing with your comments, I'd suggest "or a number" rather than "and" which could suggest something such as "even3" as being valid.

**Comment by Famlam** [comment]
Agreed, would you like to make this edit?

**Comment by FredericBourgeon** [comment]
> Agreed, would you like to make this edit?

I hope I've done it the right way on the second time. All through Github web interface, which is quite nifty.

**Review by Famlam — APPROVED** [review]
Thank you, it looks correct to me :)

**Pull request merged**
