### PR TITLE
Fix postcode test

### PR DESCRIPTION
**Pull request by Famlam**
The test was failing due to wiki update https://en.wikipedia.org/w/index.php?title=List_of_postal_codes&diff=1153347765&oldid=1151168639

This switches to a different country with the same scheme as previously listed for the US

### CODE REVIEW

**Comment by frodrigo** [comment]
Better switch last US test to `addr:postcode` tag, doesn't ?

**Comment by Famlam** [comment]
Depends on what you want to have tested. I thought it would make sense to test the same code evaluation as before, rather than stick to the country?

**Comment by frodrigo** [comment]
With the list of existing tests I think it as about countries, but we can make both ^^.

**Comment by Famlam** [comment]
Haha :)

I'm fine with doing so, however...
I suspect the user actually broke the wiki page (in which case we'll see many errors soon in that country I guess). For the US, he changed
`| NNNNN, NNNNN-NNNN` to
`| NNNN` + `|NNNNN-NNNN`, whereas his comment seems to suggest it should be  
`| NNNNN` + `|NNNNN-NNNN`

So I'm a bit hesitant to add a test for US now...
(And I'm not a local or any other way familiar with the US postal code system, so I won't edit the wiki myself)

**Comment by frodrigo** [comment]
I fixed the US postcode to five N on the wikipage.

**Comment by Famlam** [comment]
Now it has:
1. a test with the new US format 
2. a test for a different country so the old format is still being tested.

**Comment by frodrigo** [comment]
Thank you.

**Pull request merged**
