### PR TITLE
Correct and add to German translations

### PR DESCRIPTION
**Pull request by sleske**
Some corrections and additions to the German translations.

### CODE REVIEW

**Comment by jocelynj** [comment]
Thanks for the translation.

We use Transifex to handle translations in fact. Can you add your translations to https://www.transifex.com/openstreetmap-france/osmose/dashboard/ instead ?

**Comment by sleske** [comment]
Translations added in Transifex. I just added them using the online editor.
Do I need to do anything else? I did not see any "publish" button or similar.

**Comment by sleske** [comment]
And BTW, maybe you could inform contributors that you do not accept pull requests for translations.
You could add a CONTRIBUTING.md, as suggested by Github ( https://help.github.com/articles/setting-guidelines-for-repository-contributors/ ). Or just mention it in README.md .

**Comment by jocelynj** [comment]
Thanks!

I check translations at least once per month, or when somebody directly requests an update. It is true that there is no button on Transifex to request an update.

Your CONTRIBUTING.md file looks a good idea. The only information on contribution that we currently have is on http://osmose.openstreetmap.fr/en/translation , which is available on the Help menu.

**Comment by jocelynj** [comment]
Your changes were pushed on ca2251af78d96f6dbb6cf3f9de7402c70b46ed85.

**Comment by sleske** [comment]
@jocelynj Thanks, that was quick.

**Pull request closed without merging**
