### PR TITLE
remove empty disabled plugin

### PR DESCRIPTION
**Pull request by stephankn**
plugin is already in disabled folder, so comment out dead code
to get rid of warning.

### CODE REVIEW

**Comment by frodrigo** [comment]
I even prefer to delete the file than apply this inconstant patch.

**Comment by stephankn** [comment]
ok, changed to a remove of this empty code blob

**Comment by frodrigo** [comment]
cc @jocelynj

**Comment by jocelynj** [comment]
@frodrigo I don't have any objection in removing disabled plugins, especially as this one was disabled a long time ago.

**Comment by frodrigo** [comment]
Ok. Let's remove this one.

**Pull request merged**
