### PR TITLE
Analyser_Merge: Replace access=public with access=yes

### PR DESCRIPTION
**Pull request by gileri**
[access=yes is recommended over acces=yes](https://wiki.openstreetmap.org/wiki/Key:access#Possible_Tagging_Mistakes)

[It's usage is also declining](https://taginfo.openstreetmap.org/tags/access=public#chronology)

### CODE REVIEW

**Comment by frodrigo** [comment]
cc @PanierAvide

**Comment by PanierAvide** [comment]
That makes sense, thanks for offering the PR :smiley:

**Comment by frodrigo** [comment]
Thank you all

**Comment by gileri** [comment]
Thank you for the quick merge !

**Pull request merged**
