### PR TITLE
Update analyser_osmosis_duplicated_geotag.py

### PR DESCRIPTION
**Pull request by didier2020**
fix issue
https://github.com/osm-fr/osmose-backend/issues/2231

### CODE REVIEW

**Comment by Famlam** [comment]
It looks good to me. Just thinking it would be nice to add a non-regression test to this analyser. (But this can also be done in a follow-up PR in my opinion)

I assume you use `ST_StartPoint(ST_Reverse(linestring))` instead of `ST_EndPoint(linestring)` for caching-related reasons? Or maybe I'm making a thinking mistake here?

**Review by Famlam — APPROVED** [review]

**Comment by didier2020** [comment]
> It looks good to me. Just thinking it would be nice to add a non-regression test to this analyser. (But this can also be done in a follow-up PR in my opinion)
> 
> I assume you use `ST_StartPoint(ST_Reverse(linestring))` instead of `ST_EndPoint(linestring)` for caching-related reasons? Or maybe I'm making a thinking mistake here?

I tested in several countries, this does not remove the errors detected with the current version
J'ai testé sur plusieurs pays, cela n'enleve pas les erreurs détéctées avec la version actuelle

**Comment by frodrigo** [comment]
> I assume you use ST_StartPoint(ST_Reverse(linestring)) instead of ST_EndPoint(linestring) for caching-related reasons? Or maybe I'm making a thinking mistake here?

Sorry I do not see that point. It the opposite of caching, it make a useless call to ST_Reverse.

> I tested in several countries, this does not remove the errors detected with the current version

You mean ST_StartPoint(ST_Reverse(linestring)) work while ST_EndPoint(linestring)  not ?

**Comment by didier2020** [comment]
> > I assume you use ST_StartPoint(ST_Reverse(linestring)) instead of ST_EndPoint(linestring) for caching-related reasons? Or maybe I'm making a thinking mistake here?
> 
> Sorry I do not see that point. It the opposite of caching, it make a useless call to ST_Reverse.
> 
> > I tested in several countries, this does not remove the errors detected with the current version
> 
> You mean ST_StartPoint(ST_Reverse(linestring)) work while ST_EndPoint(linestring) not ?

dans le code en production, le controle est  ST_StartPoint... =  ST_StartPoint... (c'est toujours vrai )
j'ai utilisé ST_Reverse car c'est l'action menée.
je n'ai pas pensé a utiliser ST_EndPoint(linestring)

**Comment by frodrigo** [comment]
Thank you. Merged, but not deployed, yet.

**Pull request merged**
