### PR TITLE
Add tag ref:FR:SIRET

### PR DESCRIPTION
**Pull request by pyrog**

### CODE REVIEW

**Comment by vinber** [comment]
3 tags / ref:FR:SIRET phone and fax
For phone and fax, i don't know if it's automatic but we need to add +33.

**Comment by frodrigo** [comment]
phone and fax are already available.

For siret, we do not need +33.

**Comment by vinber** [comment]
ok, but next line concern only phone with 10 numbers and a 0 ? 
In our case, in "finess" it seem to be only phone number with 9 numbers but i not sure to understand "code"

**Comment by frodrigo** [comment]
this PR is not about phone. We already have phone implement.

**Comment by vinber** [comment]
Sorry I misread, misunderstood what was written in the code.

**Comment by pyrog** [comment]
> In our case, in "finess" it seem to be only phone number with 9 numbers but i not sure to understand "code"

Oups, j'ai fait un copier/coller trop rapide. Rien à voir effectivement avec les n° de téléphones.

**Comment by frodrigo** [comment]
Online.

**Pull request merged**
