### PR TITLE
Add check for bicycle=no|use_sidepath in combination with cycleway=

### PR DESCRIPTION
**Pull request by danfos**
Far from sure this is the correct way to add a new test and if the code is correct but I would like to add a check for bicycle=no|use_sidepath in combination with cycleway=, I think the code is reasonable clear on what is it is meant to do.

See https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath on the why:

_Please do not use bicycle=use_sidepath in combination with cycleway=track on the main highway, if there is no separate cycleway drawn on the map. This is confusing for routing engines because bicycle=use_sidepath indicates not to route on the main highway (use the separate cycleway) and this conflicts with the tag cycleway=track, which indicates that bicycles are allowed to route on (bike lanes connected to) the main highway._

The allowed values for cycleway= are based on https://taginfo.openstreetmap.org/keys/cycleway#values

Questions I have:
- Good idea?
- Good to re-use error class 30328, I see that now reporting only "highway=cycleway with cycleway=track", http://osmose.openstreetmap.fr/en/errors/?item=3032&class=30328
- I see there is also a plugins/Bicycle.validator.mapcss file should that also be updated?

### CODE REVIEW

**Comment by frodrigo** [comment]
I think the idea is good.

The plugins/Bicycle.validator.mapcss is the source, where the test must be written. plugins/Bicycle.py is a generated file from the mapcss using the tools mapcss2osmose from the mapcss directory.

```css
        # way["bicycle"="no|use_sidepath"]["cycleway"]["cycleway"!="no|none|separate"];
        # way["bicycle"="no|use_sidepath"]["cycleway:left"]["cycleway:left"!="no|none|separate"];
        # way["bicycle"="no|use_sidepath"]["cycleway:right"]["cycleway:right"!="no|none|separate"];
```

Report this to the mapcss file, add some asserts. You should not use `=` but regex match.
Look at https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation for the mapcss language.

You can check the mapcss file in JOSM. If you don't have the ability to generate the python file I will do it.

I think all this part is completely doc less.

**Comment by danfos** [comment]
Generating the python file proved to be easier than trying the code in JOSM so I did so.
I see Travis does see a problem with the code, let me have a look at it.

**Comment by danfos** [comment]
Understood why there is a problem, should check if the key is present before checking if the key value != no|none|separate

Let me upload the updated code, not 100% sure the generated code is correct though

**Comment by danfos** [comment]
It looks one step further, the code did pass the asserts I think but I re-useing error class 30328 was not a good idea I think, it looks like the original error class is overwitten and, as the parameters are a bit different, the higher layer code is not seeing what it is expecting.

Let me change it to use a new class, 30329.

**Comment by danfos** [comment]
Also changing the code to use a new class, 30329 is still triggering an error.

Not 100% sure what to do, should the front-end also be update or should something else be done?

**Comment by frodrigo** [comment]
Just ignore this Travis test error. It is not directly linked to your changes. The tests contains a small OSM extract, and your commit change the result on it.

**Comment by frodrigo** [comment]
It looks good for me now.

**Comment by danfos** [comment]
Thanks for checking, good to know the latest code is okay.

**Comment by frodrigo** [comment]
Merged. Thank.

**Comment by danfos** [comment]
Thanks for merging, I see the data is now available:

http://osmose.openstreetmap.fr/en/errors/?item=3032&class=30329

Not too much problems apart from [brazil_sao_paulo](http://osmose.openstreetmap.fr/en/errors/?source=37211&item=3032&class=30329)

**Comment by frodrigo** [comment]
We just deploy yesterday late. It take 24h to update the full planet.

**Pull request merged**
