### PR TITLE
Fix #2095, #1471, #803 - fix fence_type vs material warning

### LINKED ISSUE #2095: Should "Fence with material tag" really be level 1?
Currently [fence type](https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_MultipleTag.py#L35) errors are level 1, which seems to be a high value for what is essentially a cosmetic tag that doesn't affect rendering or routing. I think it should be level 3 to match the similar cosmetic tag errors like `area=yes` on relations, brand name,  missing altitude, etc.

### PR DESCRIPTION
**Pull request by Famlam**
1. Lower the priority of the `Fence with material tag, better use fence_type tag` warning (#2095)
2. Make clear that the intention is to add a fence_type, not to remove the material (e.g. `fence_type=chain_link + material=metal`) (#1471, #803)
3. Convert to mapcss so it can also be loaded into JOSM. (Uses placeholders to avoid people from translating `material` or `fence_type`; also drops the tag `highway` (unrelated) and the tag `fix:chair` (as from my chair I probably won't be able to distinguish values like `barbed_wire` from `wire`; usually it'll require a survey)

### CODE REVIEW

**Comment by frodrigo** [comment]
Nice. Thank you.

**Comment by Famlam** [comment]
@frodrigo Did I do something wrong?
It seems that the subtitle of the issues now contains `Fence with material tag, also add fence_type` (as expected), but the title is still `Fence with material tag, better use fence_type tag` (the old title)

Example:
https://osmose.openstreetmap.fr/en/issue/5607e6f7-cd01-7fda-9b08-45610d0c4bca

**Comment by frodrigo** [comment]
> @frodrigo Did I do something wrong? It seems that the subtitle of the issues now contains `Fence with material tag, also add fence_type` (as expected, this is the new text), but the title is still `Fence with material tag, better use fence_type tag` (the old title), and the priority is still "high" (instead of low) and the link still refers to [TagFix_MultipleTag.py](https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_MultipleTag.py#L35) instead of TagFix_MultipleTag2.validator.mapcss.
> 
> Example: https://osmose.openstreetmap.fr/en/issue/5607e6f7-cd01-7fda-9b08-45610d0c4bca

It is now OK.

**Comment by Famlam** [comment]
Thanks! Only the link is incorrect, but that's because the fix hasn't been merged into `master` yet

**Pull request merged**
