### PR TITLE
Analyser for defibrillators in France (GeoDAE)

### PR DESCRIPTION
**Pull request by PanierAvide**
Analyser for merging defibrillators from recently published national database.

### CODE REVIEW

**Comment by frodrigo** [comment]
Nice, It should disable some of already existing one ?
cc @wadouk

**Comment by PanierAvide** [comment]
Probably not, as national database isn't reusing (yet ?) all existing city/department databases. A fast check shows that only Paris and St-Malo might overlap with national database.

**Comment by frodrigo** [comment]
Ok. Thank. Anyway, enable your new analyser in the config

**Comment by PanierAvide** [comment]
Done :grin:

**Comment by frodrigo** [comment]
Can you review and fix the code (lint) according to CI, please ? (modules.SourceVersion.Test it already fails)

**Comment by PanierAvide** [comment]
Lint tests are fixed

**Comment by frodrigo** [comment]
Thank you.

**Pull request merged**
