### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ComradeRamen**

### CODE REVIEW

**Comment by frodrigo** [comment]
@jocelynj There is a typo in an extract name.

**Comment by frodrigo** [comment]
@ComradeRamen Bu the issue is still here. Can you tell us again on witch name the problem is ?

The issue is that not only to be fixed on Osmose side, but also on download.openstreetmap.fr

**Comment by ComradeRamen** [comment]
Didn't mean to close. I'll find it in the morning

**Comment by ComradeRamen** [comment]
https://github.com/osm-fr/osmose-backend/pull/2245

**Pull request closed without merging**
