### PR TITLE
Reaccentue module for SIRENE shop analyser

### PR DESCRIPTION
**Pull request by PanierAvide**
Solves #858

I'm not sure if `reaccentue` code and dictionnary should go into `modules` folder.

### CODE REVIEW

**Comment by frodrigo** [comment]
Please can you move the dictionary to `dictionaries` and review the travis lint.

**Comment by PanierAvide** [comment]
Should be fixed

**Comment by frodrigo** [comment]
Please, can you rebase.

**Comment by PanierAvide** [comment]
Rebase is done.

**Comment by frodrigo** [comment]
Can you remove `osm_pbf_parser.so` from the PR.

**Comment by frodrigo** [comment]
It look to work well on accent. But leave strange capital string like this
* La BOUlaNGERIE des Amis
* Le Laboratoire de la Pâtisserie ESSENTIELle
* La Droguerie PEY-BERlaND Depuis 1923
[names.txt.zip](https://github.com/osm-fr/osmose-backend/files/4618053/names.txt.zip)

**Comment by PanierAvide** [comment]
Fixed the issue on names and rebased commits.

**Comment by frodrigo** [comment]
There is still strange result. But it seem acceptable for me.
I dint know whnat you can do or not.

Are you able to do it bit better or not?
* Le Marché Bio E.leCleRC
* Tabac Presse Pas À Pas                                                                                                                                                                                                                        
* Tabac Presse Place de L'eglise
* Kerner Matériel Médical et PARAMédical
* La Petite PlaYA                                                                                                                                                                                                                               
* La TAGLIATELla

**Comment by PanierAvide** [comment]
That's weird because replace in substring bug may have been fixed by last commit (see [results in Ille-et-Vilaine](https://github.com/osm-fr/osmose-backend/files/4621628/names.txt)). In which department are these names causing issues ?

**Comment by frodrigo** [comment]
I test with Gironde. But there is less than my first try.

**Comment by PanierAvide** [comment]
OK, will try on Gironde also to see what causes this.

**Comment by PanierAvide** [comment]
Tried on Gironde with same code, can't reproduce issues on name : 
[names.txt.gz](https://github.com/osm-fr/osmose-backend/files/4621927/names.txt.gz)

**Comment by PanierAvide** [comment]
Does the version you used for testing contain `majRes` variable in `reaccentue` function ? That's the use of a list instead of replace in same string which fixes the issue.

**Comment by PanierAvide** [comment]
See https://github.com/osm-fr/osmose-backend/pull/862/files#diff-9d81e086a9332712fd3efd31cf9eb4e6R105

**Comment by frodrigo** [comment]
Event the output on Gironde is not the same list. There a diff somewhere but I cannot find it. So it i is ok for me.

**Comment by frodrigo** [comment]
Thank you!

**Pull request merged**
