### PR TITLE
Update untagged and area issue strings

### PR DESCRIPTION
**Pull request by SilentSpike**

### CODE REVIEW

**Comment by frodrigo** [comment]
Ok. But waiting for @jocelynj  about f-strings.

**Comment by SilentSpike** [comment]
I did notice the `merge_doc` method doesn't seem to be adding the list of tags where already implemented. Example: https://osmose.openstreetmap.fr/en/error/4d24f718-81ab-fb83-b91f-68997b3e789d

**Comment by frodrigo** [comment]
You are right, it is not working, at least for plugins. https://github.com/osm-fr/osmose-backend/issues/756

**Comment by frodrigo** [comment]
Thank you.

**Pull request merged**
