### PR TITLE
Add major german supermarket brands to UpperCase Validator whitelist

### PR DESCRIPTION
**Pull request by malteger**
As listed at https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&cc=de

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank you. Merged, but not deployed, yet.

Not, Osmose already use NSI, this may be done globally and automatically.

**Comment by malteger** [comment]
Oh, I did not see that. Does the NSI check for brands prevent this validator from running, or will the uppercase brands still be marked?

**Comment by frodrigo** [comment]
> Oh, I did not see that. Does the NSI check for brands prevent this validator from running, or will the uppercase brands still be marked?

There is no linked between the two. That what I suggested in my note.

**Comment by malteger** [comment]
So automatically adding relevant brands from NSI to the whitelist. I will have a look and see if I can implement it.

**Pull request merged**
