### PR TITLE
Analyse merge_fuel_FR : use daily file

### PR DESCRIPTION
**Pull request by PanierAvide**
Related to https://github.com/osm-fr/osmose-backend/issues/747

### CODE REVIEW

**Comment by frodrigo** [comment]
I got error on testing. Need to look more
```
2020-03-06 21:01:37   error: error on analyse merge_fuel_FR...
2020-03-06 21:01:37     Traceback (most recent call last):
2020-03-06 21:01:37       File "./osmose_run.py", line 230, in execc
2020-03-06 21:01:37         analyser_obj.analyser()
2020-03-06 21:01:37       File "/home/fred/frodrigo-osmose-backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2020-03-06 21:01:37         self.analyser_osmosis_common()
2020-03-06 21:01:37       File "/home/fred/frodrigo-osmose-backend/analysers/Analyser_Merge.py", line 899, in analyser_osmosis_common
2020-03-06 21:01:37         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2020-03-06 21:01:37       File "/home/fred/frodrigo-osmose-backend/analysers/Analyser_Merge.py", line 658, in run
2020-03-06 21:01:37         parser.import_(table, self.srid, osmosis)
2020-03-06 21:01:37       File "/home/fred/frodrigo-osmose-backend/analysers/Analyser_Merge.py", line 533, in import_
2020-03-06 21:01:37         values)
2020-03-06 21:01:37       File "/home/fred/frodrigo-osmose-backend/osmose-backend-venv/lib/python3.7/site-packages/psycopg2/extras.py", line 142, in execute
2020-03-06 21:01:37         return super(DictCursor, self).execute(query, vars)
2020-03-06 21:01:37     UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 7: ordinal not in range(128)

```

**Comment by PanierAvide** [comment]
I made a change in `GeoJSON` class in `Analyser_merge.py` to read all features properties to not miss any column (it was only reading first feature before, so any property not appearing in first one but elsewhere was causing issues). This was running smoothly on merge_fuel_FR though.

**Comment by frodrigo** [comment]
Was a setup issue on my side. It is ok for me.

**Comment by frodrigo** [comment]
Thank you.

**Comment by frodrigo** [comment]
Results are online.

**Pull request merged**
