### PR TITLE
Merge bus stops in Kerala, India

### PR DESCRIPTION
**Pull request by nlehuby**

### CODE REVIEW

**Comment by nlehuby** [comment]
Thanks ! Please let me know when it is released

**Comment by nlehuby** [comment]
Hey ! This analysis seems to not be available yet, 2 months later :thinking: Is there something wrong ?

**Comment by frodrigo** [comment]
@stephankn It should run on your backend.
Please could you check the logs about india_kerala ?

**Comment by stephankn** [comment]
Backend is on latest revision on docker image. Analyzer fails. Call stack:
```
2021-09-09 03:54:17 india_kerala : merge_public_transport_IN_kerala_bus
2021-09-09 03:54:17   error: error on analyse merge_public_transport_IN_kerala_bus...
2021-09-09 03:54:17     Traceback (most recent call last):
2021-09-09 03:54:17       File "./osmose_run.py", line 232, in execc
2021-09-09 03:54:17         with obj(analyser_conf, logger.sub()) as analyser_obj:
2021-09-09 03:54:17       File "/opt/osmose-backend/analysers/analyser_merge_public_transport_IN_kerala_bus.py", line 52, in __init__
2021-09-09 03:54:17         "name": lambda res: res["Name"].title()
2021-09-09 03:54:17     TypeError: __init__() got an unexpected keyword argument 'select'
```

**Comment by stephankn** [comment]
@frodrigo what kind of tests are executed before the merge? Unfortunately Python has no compiler, which would have detected early that the call to `Mapping` is wrong. My best guess is that here a call to `Conflate` was intended.

Is there a way to prevent obviously untested code which was never executed before being merged?

**Comment by frodrigo** [comment]
> @frodrigo what kind of tests are executed before the merge? Unfortunately Python has no compiler, which would have detected early that the call to `Mapping` is wrong. My best guess is that here a call to `Conflate` was intended.
> 
> Is there a way to prevent obviously untested code which was never executed before being merged?

There is validation and tests on some part. But here the python code is valid, but cannot be executed. We does not run test this kind of analyzer.

**Comment by nlehuby** [comment]
fix in #1330

**Comment by stephankn** [comment]
```
2021-09-15 04:59:38 india_kerala : merge_public_transport_IN_kerala_bus
2021-09-15 04:59:38   error: Fails to get status from frontend: 404
2021-09-15 04:59:38   run osmosis all analyser Analyser_Merge_Public_Transport_IN_Kerala_Bus_Stops
2021-09-15 04:59:41   Analyser_Merge.py:1143 sql
2021-09-15 04:59:41   Analyser_Merge.py:775 sql
2021-09-15 04:59:41   Analyser_Merge.py:780 sql
2021-09-15 04:59:41   Load source into database
2021-09-15 04:59:41   Analyser_Merge.py:783 sql
2021-09-15 04:59:41   Analyser_Merge.py:791 sql
2021-09-15 04:59:41   Analyser_Merge.py:793 sql
2021-09-15 04:59:42   Analyser_Merge.py:795 sql
2021-09-15 04:59:42   Analyser_Merge.py:796 sql
2021-09-15 04:59:42   Analyser_Merge.py:797 sql
2021-09-15 04:59:42   Analyser_Merge.py:798 sql
2021-09-15 04:59:42   Analyser_Merge.py:811 sql
2021-09-15 04:59:42   Convert data to tags
2021-09-15 04:59:42   Analyser_Merge.py:820 sql
2021-09-15 04:59:42   Analyser_Merge.py:821 sql
2021-09-15 04:59:42   Analyser_Merge.py:870 sql
2021-09-15 04:59:45   Analyser_Merge.py:871 sql
2021-09-15 04:59:45   Analyser_Merge.py:877 sql
2021-09-15 04:59:45   Analyser_Merge.py:878 sql
2021-09-15 04:59:45   Analyser_Merge.py:883 sql
2021-09-15 04:59:45   Analyser_Merge.py:885 sql
2021-09-15 04:59:45   Analyser_Merge.py:886 sql
2021-09-15 04:59:45   Analyser_Merge.py:887 sql
2021-09-15 04:59:45   Retrieve OSM item
2021-09-15 04:59:45   Analyser_Merge.py:1190 sql
2021-09-15 04:59:45   Analyser_Merge.py:1196 sql
2021-09-15 04:59:45   Analyser_Merge.py:1208 sql
2021-09-15 04:59:45   Analyser_Merge.py:1209 sql
2021-09-15 04:59:45   Analyser_Merge.py:1211 xml generation
2021-09-15 04:59:47   update
2021-09-15 04:59:47     iteration=1
2021-09-15 05:00:01     OK
```

3416 findings had been uploaded:
http://osmose.openstreetmap.fr/en/issues/open?source=424977&item=8040&class=61

**Comment by frodrigo** [comment]
Good, thank you all.

**Pull request merged**
