### PR TITLE
Make Dutch addr:housenumber warnings less strict

### LINKED ISSUE #711: Invalid addr:housenumber value, false positives in The Netherlands
item | 2060, class | 10
Recently I noticed a great number of this issues on the map.
As an example: http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=51.402247&lon=3.538166&item=2060&level=1%2C2%2C3&tags=&fixable=
In The Netherlands the street-names, house-numbers and postcode are established by the municipality.
These house-numbers are not just **numbers**, but *can* include hyphen and characters (both upper- and/or lowercase).
Examples of **valid** identifiers are "44-bis", "1-TRAF", "19p-8", "44d-G", "48A", "49a", "3-0072", "450-482".

Many (but not all) of these 'odd' numbers are given to a block of garages, chalets, apartments, service-buildings etc. and there are nearby more addresses according that pattern.

### PR DESCRIPTION
**Pull request by jdhoek**
Fixes #711.

Work in progress.

### CODE REVIEW

**Comment by frodrigo** [comment]
Still a work in progress ?

Want this work be merged for now ?

**Comment by jdhoek** [comment]
Wait a bit if you don't mind. We are currently bikeshedding this in the Dutch OSM community.

**Comment by jdhoek** [comment]
@frodrigo I'm fine with merging this as it stands. This PR should at the very least reduce the number of warnings, reducing the check to obvious errors. It fixes the biggest issue with @danfos contribution, (overlooking `-` in valid places), and includes support for a number of edge cases in Dutch house numbers.

There has been some bikeshedding on this in the Dutch community, but in my opinion nothing that should stop this PR from being merged, as it is an improvement on the current situation in any case. All test case suggestions made there have been added to this PR.

**Comment by jdhoek** [comment]
I'm not sure why the Travis CI check fails. The tests run fine with `pytest`.

**Comment by jdhoek** [comment]
Never mind, that Travis failure looks like an `apt install` failure that cannot be related to this specific PR.

**Comment by frodrigo** [comment]
Merged. Thank you. The code still need to be deployed manually cc @jocelynj

**Comment by frodrigo** [comment]
Update is in progress, you can check the first results
http://osmose.openstreetmap.fr/en/errors/?country=netherlands_*&item=2060&class=10

**Pull request merged**
