### PR TITLE
(Attempt to) stop jumping markers for duplicate wiki pages

### PR DESCRIPTION
**Pull request by frodrigo**
Complementary to #1922

### CODE REVIEW

**Comment by Famlam** [comment]
Thank you! I'll review it tomorrow!

**Comment by Famlam** [comment]
I had to confirm this for myself with a real run on an extract (results below), but by setting the first value already in `tid` in `b`, the `(array_agg(tid))[1:10]` will just grab the first element 10 times, instead of grabbing the first 10 elements (of the 19 in total for this case). 

E.g., the following result (part of the results from Gelderland) just refers to node 10285752983 ten times.
```xml
<error class="1">
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285752983" lat="51.8119529" lon="5.2496313" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-65" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<location lat="51.8119529" lon="5.2496313" />
<text lang="en" value="nl:Lijst van Stolpersteine in Zaltbommel" />
</error>
```

**Comment by frodrigo** [comment]
You are right, fixed.

**Comment by Famlam** [comment]
It can happen that the location marker is not among the 10 selected markers:

```xml
<error class="1">
<node id="10285764699" lat="51.812561200000005" lon="5.249001000000001" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-39" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285802504" lat="51.811241800000005" lon="5.2477915" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/nonnenstraat-26" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285814509" lat="51.811469100000004" lon="5.250092400000001" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-91" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285856710" lat="51.81425350000001" lon="5.2491678" version="1" user="FrankOverman">
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285846649" lat="51.8142038" lon="5.247451900000001" version="1" user="FrankOverman">
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285841267" lat="51.8139735" lon="5.249499500000001" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/gasthuisstraat-31" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285787767" lat="51.8125597" lon="5.2499210000000005" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/ruiterstraat-15" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285840406" lat="51.8132706" lon="5.2482663" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-13" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285806581" lat="51.8116859" lon="5.2497561" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/boschstraat-72" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<node id="10285806580" lat="51.8087266" lon="5.255040500000001" version="1" user="FrankOverman">
<tag k="url" v="https://map.stolpersteine.app/nl/zaltbommel/locaties/koningin-wilhelminaweg-44" />
<tag k="historic" v="memorial" />
<tag k="memorial" v="stolperstein" />
<tag k="wikipedia" v="nl:Lijst van Stolpersteine in Zaltbommel" />
</node>
<location lat="51.8119529" lon="5.2496313" />
<text lang="en" value="nl:Lijst van Stolpersteine in Zaltbommel" />
</error>
```

The marker corresponds to node https://www.openstreetmap.org/node/10285752983, which isn't in the list. Maybe you need to ORDER BY id?

**Comment by Famlam** [comment]
It seems to work ok now 👍

**Review by Famlam — APPROVED** [review]

**Review by Famlam — APPROVED** [review]

**Pull request merged**
