### PR TITLE
Enabling stop sign recognition for Oklahoma.

### PR DESCRIPTION
**Pull request by BalooUriza**
Suggested by Frédéric in #576.

### CODE REVIEW

**Comment by BalooUriza** [comment]
Would like to see how this performs on Oklahoma prior to expanding it to the rest of the US.

**Comment by frodrigo** [comment]
Thank. Merged, but not deployed yet.

**Comment by BalooUriza** [comment]
No problem.  Is there an estimate for when this will go live?

**Comment by frodrigo** [comment]
No. When we push the button.

**Pull request merged**
