### PR TITLE
added motorways to oneways

### PR DESCRIPTION
**Pull request by ComradeRamen**
oneway=yes is implied for highway=motorway. See [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway)

### CODE REVIEW

**Comment by ComradeRamen** [comment]
oneway=yes is implied for highway=motorway. See [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway)

**Comment by frodrigo** [comment]
Good spot. Thank you.
Before merge we need a quick check that will not have side effects on analyzers.

**Comment by ComradeRamen** [comment]
I noticed this omission when there were no motorways in the issues I downloaded.
 
I've been manually sorting the issue:[One way inaccessible or missing parking or parking entrance] so I can find higher classification highways since most of the detections are service roads. 

Would love if the website allowed such sorting natively but I'm not sure if I have the technical expertise for that.

**Comment by ComradeRamen** [comment]
Especially since I recently came across a reversed motorway_link in the US that had been live on the database for ~10 months.

**Comment by Famlam** [comment]
I would leave out the oneway!=no, and only check that there's no oneway tag. If there is a oneway tag, then the "or" behind it should catch it

I think that most analysers have roundabouts and motorways hardcoded, but some use motorways as "starting points"

**Comment by Famlam** [comment]
> Especially since I recently came across a reversed motorway_link in the US that had been live on the database for ~10 months.

Likely this won't be spotted anyway, there's no check against very sharp angles when entering a motorway, and this analyser is among those that use motorways as starting points

**Comment by ComradeRamen** [comment]
> only check that there's no oneway tag. If there is a oneway tag, then the "or" behind it should catch it

Wouldn't this make the code less understandable at a glance; or is this an issue of efficiency?

**Comment by Famlam** [comment]
> > only check that there's no oneway tag. If there is a oneway tag, then the "or" behind it should catch it
> 
> Wouldn't this make the code less understandable at a glance; or is this an issue of efficiency?

I would personally argue it makes it more easy to read as you only have to consider values of oneway once.

Remember there's also other values of oneway, like "alternating" and "reversible", which aren't a true oneway, but still override the default of motorway

**Comment by ComradeRamen** [comment]
> leave out the oneway!=no, and only check that there's no oneway tag.

Done. (I think)

**Comment by ComradeRamen** [comment]
> > Especially since I recently came across a reversed motorway_link in the US that had been live on the database for ~10 months.
> 
> Likely this won't be spotted anyway, there's no check against very sharp angles when entering a motorway, and this analyser is among those that use motorways as starting points

It was a very short segment in the middle of a long ramp. The connecting _links were the correct orientation

**Comment by ComradeRamen** [comment]
Can someone merge this please?

**Comment by Famlam** [comment]
I have no principal objections here, but I think this is why it hasn't been merged yet:

> Before merge we need a quick check that will not have side effects on analyzers.


I haven't had the time for that yet.
(In a second step we probably also have to clean up the analysers that have their own code for motorway)

**Comment by Famlam** [comment]
Please revert the latest change (to analyser_osmosis_highway_deadend), here motorways (and a couple of other ones) are purposefully used as input points

**Comment by ComradeRamen** [comment]
Should it be a separate pull request? Isn't this endpoint inclusion unnecessary since they're now defined as oneways already and thus already included in endpoints?

**Comment by Famlam** [comment]
> Should it be a separate pull request? Isn't this endpoint inclusion unnecessary since they're now defined as oneways already and thus already included in endpoints?

Regarding *_deadend: here they're purposefully included together with *non*-oneways, for the simple reason that motorways are very high on the hierarchy network. (This analyser is based on "travelling" through the road network to find deadends)

I had a quick look (just searching all uses of is_oneway), probably my comment about cleanup was unnecessary as there's no cases where it says `is_oneway OR highway='motorway'` or similar

**Comment by ComradeRamen** [comment]
> Regarding *_deadend: here they're purposefully included together with _non_-oneways, for the simple reason that motorways are very high on the hierarchy network. (This analyser is based on "travelling" through the road network to find deadends)

Since this is supposed to add "valid input nodes" my understanding is that without removal it would count this as a valid connection. What am I missing?
image

**Comment by Famlam** [comment]
> What am I missing?

That this is not `is_oneway` related, unlike the remainder of the PR. I understood your earlier comment "since they're now defined as oneways already" that you wanted to remove it because it's now a oneway.

The origin of this exception stems from here: https://github.com/osm-fr/osmose-backend/issues/231. That issue should have been solved by that we nowadays include all nodes from "border crossing ways" as safe points.

We could look into how it behaves without that exception (especially with island regions), but not in this PR. Probably it'll be ok to remove, assuming that every island with a motorway also has at least either a ferry terminal connected to the road network or a non-oneway road somewhere.

**Comment by ComradeRamen** [comment]
Is there a way to see what caused the extra detection in the failed test?

**Review by Famlam — APPROVED** [review]
I checked the results of jersey, netherlands_gelderland and switserland_basel_stadt with and without this change, results seem ok to me :)

**Comment by Famlam** [comment]
> Is there a way to see what caused the extra detection in the failed test?

It's dummy test data, see `\tests\osmosis_highway_deadend.osm`. Probably node 55 was detected, which makes sense with your modification (and isn't bad to detect, so don't worry too much about this). But lets discuss this in a separate PR (after this one is merged).
Likely you'll need to add `self.check_err(cl="3", elems=[("node", "65"), ("way", "1028")])` to the tests near line 540 and increase the count of 22 to 23 at the final line.

**Comment by frodrigo** [comment]
Merged, but not deployed yet.

**Pull request merged**
