### PR TITLE
PT: adding sax checks on route and route_master

### PR DESCRIPTION
**Pull request by prhod**

### CODE REVIEW

**Comment by frodrigo** [comment]
Ok, as new checked fields are "recommended". (Note, Osmose QA should report for issues, not missing improvment.)

**Comment by prhod** [comment]
Thanks for the note, I'll be careful about that!

**Comment by frodrigo** [comment]
The first results are available.
http://osmose.openstreetmap.fr/fr/errors/?country=france_ile_de_france&item=2140
Please, do a review of the results if necessary.

**Comment by jocelynj** [comment]
Note that it breaks some unit-level tests on this plugin:
```
$ nosetests plugins/Public_Transport_Route.py
F
======================================================================
FAIL: test (plugins.Public_Transport_Route.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../backend/plugins/Public_Transport_Route.py", line 97, in test
    assert not a.relation(None, t, None), t
AssertionError: {'route_master': 'bus', 'type': 'route_master'}

----------------------------------------------------------------------
```

@prhod: do you know how to fix the tests ?  (the fail is because the test doesn't expect any issue to be reported with tags `{'route_master': 'bus', 'type': 'route_master'}`)

**Comment by prhod** [comment]
Thanks for the merge and spotting the unit-tests. I made a new PR (https://github.com/osm-fr/osmose-backend/pull/230) to fix them.

**Pull request merged**
