### PR TITLE
Update TagFix_BadValue.py with sport exceptions

### PR DESCRIPTION
**Pull request by nicorikken**
I noticed false flags in Osmose on the sport types. This commit adds all valid sport types currently listed on the OpenStreetMap wiki https://wiki.openstreetmap.org/wiki/Key:sport that are exceptions to the general regex.

Signed-off-by: Nico Rikken <nico@nicorikken.eu>

### CODE REVIEW

**Comment by frodrigo** [comment]
No need of exception for when use "_"

Also see https://github.com/osm-fr/osmose-backend/issues/1052#issuecomment-744030756

**Comment by nicorikken** [comment]
@frodrigo Thanks, I drew the wrong conclusion based on the regex. Now the list of exceptions is much smaller :smile:

**Comment by frodrigo** [comment]
Thank you.

**Comment by nicorikken** [comment]
@frodrigo Thanks for merging! Happy to contribute a fix that helps other Osmose users. :heart:

**Pull request merged**
