### PR TITLE
Building indoor

### PR DESCRIPTION
**Pull request by didier2020**
fix false positive for indoor mapping

### CODE REVIEW

**Comment by frodrigo** [comment]
min_height is more linked to 3D than indoor.

**Comment by didier2020** [comment]
intersections are "not true" when tagging indoor or 3D

**Comment by frodrigo** [comment]
The point is not about ignoring the indoor (I am pro), but the way you detect it.

**Comment by didier2020** [comment]
building don't overlaps :
http://osmose.openstreetmap.fr/fr/error/cf6626a2-e347-8474-6fa2-586a64170192

**Comment by frodrigo** [comment]
I am telling min_height is not directly liked to inddor.

**Comment by didier2020** [comment]
it's ok.

**Comment by didier2020** [comment]
analysis is ok, if there are errors it comes from the tags used.
so i close the branck

**Pull request closed without merging**
