### PR TITLE
Translation for zh-cn

### PR DESCRIPTION
**Pull request by AustinZhu**
Translated a few strings in zh_CN.po

### CODE REVIEW

**Comment by jocelynj** [comment]
Thanks for the translation, but we are in fact handling translations through transifex:
https://www.transifex.com/openstreetmap-france/osmose/

Can you move these translations to transifex?

**Comment by AustinZhu** [comment]
Sorry for not reading the project description thoroughly.

I will move them to transifex later.

**Comment by frodrigo** [comment]
Can we close this?

**Comment by jocelynj** [comment]
Closing as translations are done on transifex.

**Pull request closed without merging**
