### PR TITLE
Fix 1640: Updated values and rules for AT:urban

### PR DESCRIPTION
**Pull request by mcliquid**
German discussion: https://community.openstreetmap.org/t/osmose-meckert-uber-tempo-50-im-ortsverkehr/5113

Solution from @frodrigo in #1640 

Thanks!

### CODE REVIEW

**Comment by Famlam** [comment]
FYI, `at:urban` is 50, which is also the default (see line 29), so no need to specify that one ;)

**Comment by Famlam** [comment]
That's probably because the current live version says the max speed in urban is 30 or 40. (I guess that's related to the conflict warning you see)

https://github.com/osm-fr/osmose-backend/commit/0c7b71007e0cd889e4f530164807bd11b3323173

**Comment by Famlam** [comment]
I'd think so; @frodrigo ?

**Comment by frodrigo** [comment]
If you define an at:urban rule it override the default and replace the value 50.

**Comment by Famlam** [comment]
You'll have to wait until one of the admins has time ;)

Meanwhile, I see "This branch has conflicts that must be resolved". Maybe you can resolve it?

**Comment by frodrigo** [comment]
Also reverting in OSRM https://github.com/Project-OSRM/osrm-backend/pull/6450

**Pull request merged**
