### PR TITLE
Differentiate extreme numerical value checks from invalid numerical value checks

### PR DESCRIPTION
**Pull request by SilentSpike**
This way the docs strings are more appropriate for these issue types (and I could see further issues of this nature being added to this class).

### CODE REVIEW

**Comment by frodrigo** [comment]
May be have tow class, to have spesific and more explicit doc?

**Comment by frodrigo** [comment]
Note for myself, add item 3092.

**Comment by SilentSpike** [comment]
Generic means less work for translators and potential to add more cases (maxspeed higher than 160 - this could even be varied by country if highest speed limits are known, street `incline` higher than the world record, etc.)

**Comment by frodrigo** [comment]
While there is more doc, I think we lose some thing very simple and understandable : "is really slow".

**Comment by frodrigo** [comment]
Pick only a part of the PR.

**Comment by SilentSpike** [comment]
👍 Apologies, have been busy with other projects and didn't get a chance to update this.

One suggestion I might make for the subtitle strings is to always put key and value in using formatting (this way the strings are more generic and could be used elsewhere too).

So
```python
"`{0}` is really slow", 'maxspeed=' + m.group(1))
```

**Comment by frodrigo** [comment]
You are right. Changed.

**Pull request closed without merging**
