### PR TITLE
MapCSS rules for France (from JOSM)

### PR DESCRIPTION
**Pull request by PanierAvide**
So I used the tool to convert from the https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules MapCSS file, and used item 9016 for this gauge on railway rule.

### CODE REVIEW

**Comment by frodrigo** [comment]
I'm impressed, you build a mapcss files!

Unfortunately most steps was necessary. I update the mapcss source file to add -osmose attributes. Then rename osmose assert attributes, and finally regenerated the python file and changing generator configuration.

**Comment by PanierAvide** [comment]
Great, thanks for having done the last steps, that makes clearer for me what is necessary to have a complete MapCSS analyzer for Osmose :-)

**Comment by frodrigo** [comment]
Result
http://osmose.openstreetmap.fr/en/map/#item=&useDevItem=all&zoom=7&lat=46.019&lon=1.472&level=1%2C2%2C3&tags=&fixable=

Item 2160 should be activated

**Comment by PanierAvide** [comment]
Yes I saw that this morning, that's great :-) Thanks for the fix and integration !

**Comment by didier2020** [comment]
I made a modification to  https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules :
remove "ref" in nodes'rule highway milestone.
Can you do an osmose update for this mapcss rule ?

**Comment by frodrigo** [comment]
@didier2020 maybe wait a bit more as we are agree?

**Comment by didier2020** [comment]
yes i can...
those who think that ref should not be a tag, do not offer an alternative

**Pull request closed without merging**
