### PR TITLE
Fix typo in Highway_Lanes

### PR DESCRIPTION
**Pull request by Famlam**
#2015

### CODE REVIEW

**Comment by Famlam** [comment]
I'm confused, it shows merged, but at the same time it doesn't appear in the commit history?

**Comment by frodrigo** [comment]
I made something odd with the branches and deploy earlier. I not see I lost a commit. It you still have it can you make a PR again or push it to dev, please ? Do you thing there is other commits missing ?

**Comment by Famlam** [comment]
No problem!
I made it in a new branch: #2021

**Comment by frodrigo** [comment]
Sorry. Thank you.

**Comment by Famlam** [comment]
No problem, these things happen ;)
I'm glad it worked well now

**Pull request merged**
