### PR TITLE
fix issues/1256 to include all Arabic tashkeel

### PR DESCRIPTION
**Pull request by hubaishan**
Adding all Arabic Tashkeel marks
as in https://unicode-table.com/en/blocks/arabic/ 
and https://www.unicode.org/charts/PDF/U0600.pdf

### CODE REVIEW

**Comment by frodrigo** [comment]
@iriman this changes make sense to you, especially on Farsi?

**Comment by hubaishan** [comment]
To avoid https://github.com/osm-fr/osmose-backend/issues/1256

**Comment by iriman** [comment]
@frodrigo Yes, these diacritics are correct for Farsi, too. But, as @hubaishan mentioned, `064F` was missing (compare with character table on page 2 of U0600.pdf)

**Comment by frodrigo** [comment]
Thank you all.

**Pull request merged**
