### PR TITLE
Update Osmosis to osmosis-0.48.3-34-gb5383475-SNAPSHOT using https://github.com/openstreetmap/osmosis/pull/134 #1951

### PR DESCRIPTION
**Pull request by frodrigo**
Update Osmosis to osmosis-0.48.3-34-gb5383475-SNAPSHOT using https://github.com/openstreetmap/osmosis/pull/134 #1951

Support of partial loop on linestring with missing start/end

### CODE REVIEW

**Comment by Famlam** [comment]
I don't know why (no time for debugging now), but when I run:
`./osmose_run.py --extract-update-tool=osmium --import-tool=osmosis-parallel --skip-frontend --skip-frontend-check --skip-upload --country=netherlands_zeeland --analyser=osmosis_relation_multipolygon`
with this PR it does include way 1059958114 in the results (the one that's supposed to be removed by closing the linestring).

When I ran Osmose using the file in https://github.com/osm-fr/osmose-backend/pull/1951#discussion_r1264679560 these results were correctly removed.

**Comment by frodrigo** [comment]
Opps, I made the PR not using the right build.
I fixed it now.
@Famlam thank for testing it !

**Comment by jocelynj** [comment]
This looks nice, thanks.

Two remarks:
  - could you add a bit more information in the commit message on why this is required?
  - how was osmosis rebuilt? As I see that almost no files are changing in the diff.

**Comment by frodrigo** [comment]
> could you add a bit more information in the commit message on why this is required?

Done

> how was osmosis rebuilt? As I see that almost no files are changing in the diff.

Using the recommended way `./docker.sh ./gradlew build`  from https://github.com/openstreetmap/osmosis/blob/main/doc/development.md

Most the package is only java dependencies. Only one jar actually contains compiled Osmosis code.

**Pull request merged**
